// <auto-generated />
using System;
using Avaratra.BackOffice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Avaratra.BackOffice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avaratra.BackOffice.Models.Alerte", b =>
                {
                    b.Property<int>("idAlerte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alerte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAlerte"));

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("dateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<int>("idTypeAlerte")
                        .HasColumnType("int")
                        .HasColumnName("id_type_alerte");

                    b.Property<int>("id_commune")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<decimal>("niveau")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("niveau");

                    b.Property<int>("typeAlerteidTypeAlerte")
                        .HasColumnType("int");

                    b.HasKey("idAlerte");

                    b.HasIndex("id_commune");

                    b.HasIndex("typeAlerteidTypeAlerte");

                    b.ToTable("Alerte");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Capteur", b =>
                {
                    b.Property<int>("idCapteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_capteur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCapteur"));

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<int>("id_commune")
                        .HasColumnType("int");

                    b.Property<int>("id_infrastructure")
                        .HasColumnType("int");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.HasKey("idCapteur");

                    b.HasIndex("id_commune");

                    b.HasIndex("id_infrastructure");

                    b.ToTable("Capteur");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Categorie", b =>
                {
                    b.Property<int>("idCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categorie");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCategorie"));

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.HasKey("idCategorie");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Commune", b =>
                {
                    b.Property<int>("idCommune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_commune");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCommune"));

                    b.Property<int>("IdDistrict")
                        .HasColumnType("int")
                        .HasColumnName("id_district");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<Point>("geometrie")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("geometrie");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("nombrePopulation")
                        .HasColumnType("int")
                        .HasColumnName("nombre_population");

                    b.HasKey("idCommune");

                    b.HasIndex("IdDistrict");

                    b.ToTable("Commune");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.District", b =>
                {
                    b.Property<int>("idDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_district");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDistrict"));

                    b.Property<int>("IdRegion")
                        .HasColumnType("int")
                        .HasColumnName("id_region");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<Geometry>("geometrie")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("geometrie");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.Property<int>("totalPopulationDistrict")
                        .HasColumnType("int")
                        .HasColumnName("total_population_district");

                    b.HasKey("idDistrict");

                    b.HasIndex("IdRegion");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Infrastructure", b =>
                {
                    b.Property<int>("idInfrastructure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_infrastructure");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInfrastructure"));

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int")
                        .HasColumnName("id_categorie");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.HasKey("idInfrastructure");

                    b.HasIndex("IdCategorie");

                    b.ToTable("Infrastructure");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Mesure", b =>
                {
                    b.Property<int>("idMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mesure");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMesure"));

                    b.Property<int>("IdCapteur")
                        .HasColumnType("int")
                        .HasColumnName("id_capteur");

                    b.Property<int>("IdTypeMesure")
                        .HasColumnType("int")
                        .HasColumnName("id_type_mesure");

                    b.Property<int>("IdUnite")
                        .HasColumnType("int")
                        .HasColumnName("id_unite");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<DateTime>("datePrise")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_prise");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<decimal>("valeur")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("valeur");

                    b.HasKey("idMesure");

                    b.HasIndex("IdCapteur");

                    b.HasIndex("IdTypeMesure");

                    b.HasIndex("IdUnite");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Mesure");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Profil", b =>
                {
                    b.Property<int>("idProfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_profil");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProfil"));

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("intitule");

                    b.HasKey("idProfil");

                    b.ToTable("Profil");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Region", b =>
                {
                    b.Property<int>("idRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_region");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRegion"));

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<Point>("geometrie")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("geometrie");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("totalPopulationRegion")
                        .HasColumnType("int")
                        .HasColumnName("total_population_region");

                    b.HasKey("idRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Responsable", b =>
                {
                    b.Property<int>("idResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idResponsable"));

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_fin");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("id_commune")
                        .HasColumnType("int");

                    b.HasKey("idResponsable");

                    b.HasIndex("idUtilisateur");

                    b.HasIndex("id_commune");

                    b.ToTable("Responsable");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Signalement", b =>
                {
                    b.Property<int>("idSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_signalement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSignalement"));

                    b.Property<DateTime>("dateSignalement")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_signalement");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<int>("idTypeSignalement")
                        .HasColumnType("int")
                        .HasColumnName("id_type_signalement");

                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("id_commune")
                        .HasColumnType("int");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<byte>("photo")
                        .HasColumnType("tinyint")
                        .HasColumnName("photo");

                    b.HasKey("idSignalement");

                    b.HasIndex("idTypeSignalement");

                    b.HasIndex("idUtilisateur");

                    b.HasIndex("id_commune");

                    b.ToTable("Signalement");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.TypeAlerte", b =>
                {
                    b.Property<int>("idTypeAlerte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_type_alerte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTypeAlerte"));

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.HasKey("idTypeAlerte");

                    b.ToTable("TypeAlerte");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.TypeMesure", b =>
                {
                    b.Property<int>("idTypeMesure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_type_mesure");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTypeMesure"));

                    b.Property<int>("IdUnite")
                        .HasColumnType("int")
                        .HasColumnName("id_unite");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.HasKey("idTypeMesure");

                    b.HasIndex("IdUnite");

                    b.ToTable("TypeMesure");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.TypeSignalement", b =>
                {
                    b.Property<int>("idTypeSignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_type_signalement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTypeSignalement"));

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("intitule")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("intitule");

                    b.HasKey("idTypeSignalement");

                    b.ToTable("TypeSignalement");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Unite", b =>
                {
                    b.Property<int>("idUnite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUnite"));

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("symbole")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("symbole");

                    b.HasKey("idUnite");

                    b.ToTable("Unite");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Utilisateur", b =>
                {
                    b.Property<int>("idUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUtilisateur"));

                    b.Property<int>("IdCommune")
                        .HasColumnType("int")
                        .HasColumnName("id_commune");

                    b.Property<int>("IdProfil")
                        .HasColumnType("int")
                        .HasColumnName("id_profil");

                    b.Property<DateTime>("dateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("dateNaissance")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_naissance");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("etat")
                        .HasColumnType("int")
                        .HasColumnName("etat");

                    b.Property<string>("motDePasse")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("prenoms")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prenoms");

                    b.HasKey("idUtilisateur");

                    b.HasIndex("IdCommune");

                    b.HasIndex("IdProfil");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Alerte", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Commune", "commune")
                        .WithMany()
                        .HasForeignKey("id_commune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.TypeAlerte", "typeAlerte")
                        .WithMany()
                        .HasForeignKey("typeAlerteidTypeAlerte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commune");

                    b.Navigation("typeAlerte");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Capteur", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Commune", "commune")
                        .WithMany()
                        .HasForeignKey("id_commune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Infrastructure", "infrastructure")
                        .WithMany()
                        .HasForeignKey("id_infrastructure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commune");

                    b.Navigation("infrastructure");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Commune", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("IdDistrict")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.District", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Infrastructure", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Mesure", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Capteur", "Capteur")
                        .WithMany()
                        .HasForeignKey("IdCapteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.TypeMesure", "TypeMesure")
                        .WithMany()
                        .HasForeignKey("IdTypeMesure")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Unite", "Unite")
                        .WithMany("mesures")
                        .HasForeignKey("IdUnite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Utilisateur", "Utilisateur")
                        .WithMany("mesures")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capteur");

                    b.Navigation("TypeMesure");

                    b.Navigation("Unite");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Responsable", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Utilisateur", "utilisateur")
                        .WithMany("responsables")
                        .HasForeignKey("idUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Commune", "commune")
                        .WithMany()
                        .HasForeignKey("id_commune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commune");

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Signalement", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.TypeSignalement", "typeSignalement")
                        .WithMany("signalements")
                        .HasForeignKey("idTypeSignalement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Utilisateur", "utilisateur")
                        .WithMany("signalements")
                        .HasForeignKey("idUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Commune", "commune")
                        .WithMany()
                        .HasForeignKey("id_commune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commune");

                    b.Navigation("typeSignalement");

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.TypeMesure", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Unite", "Unite")
                        .WithMany()
                        .HasForeignKey("IdUnite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Utilisateur", b =>
                {
                    b.HasOne("Avaratra.BackOffice.Models.Commune", "Commune")
                        .WithMany()
                        .HasForeignKey("IdCommune")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avaratra.BackOffice.Models.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("IdProfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");

                    b.Navigation("Profil");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.TypeSignalement", b =>
                {
                    b.Navigation("signalements");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Unite", b =>
                {
                    b.Navigation("mesures");
                });

            modelBuilder.Entity("Avaratra.BackOffice.Models.Utilisateur", b =>
                {
                    b.Navigation("mesures");

                    b.Navigation("responsables");

                    b.Navigation("signalements");
                });
#pragma warning restore 612, 618
        }
    }
}
